apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    vault:
      server: {{ .Values.clusterSecretStore.vault.server | quote }}
      path: {{ .Values.clusterSecretStore.vault.path | quote }}
      version: {{ .Values.clusterSecretStore.vault.version | quote }}

      auth:
        appRole:
          path: {{ .Values.clusterSecretStore.vault.appRole.path | quote }}

          roleRef:
            name: {{ .Values.clusterSecretStore.vault.appRole.credentialsSecret.name }}
            namespace: {{ .Values.clusterSecretStore.vault.appRole.credentialsSecret.namespace }}
            key: {{ .Values.clusterSecretStore.vault.appRole.credentialsSecret.roleIdKey }}

          secretRef:
            name: {{ .Values.clusterSecretStore.vault.appRole.credentialsSecret.name }}
            namespace: {{ .Values.clusterSecretStore.vault.appRole.credentialsSecret.namespace }}
            key: {{ .Values.clusterSecretStore.vault.appRole.credentialsSecret.secretIdKey }}