{{- range .Values.externalSecrets }}
{{- if .enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  refreshInterval: {{ .refreshInterval }}

  secretStoreRef:
    name: {{ .secretStoreRef.name }}
    kind: ClusterSecretStore

  target:
    name: {{ .target.name }}
    creationPolicy: Owner

    {{- if .target.template }}
    template:
      engineVersion: v2
      data:
        {{- toYaml .target.template.data | nindent 8 }}
    {{- end }}

  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}